apiVersion: postgresql.cnpg.io/v1
kind: Pooler

metadata:
  name: myapp-db-pooler
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: database-pooler

spec:
  cluster:
    name: myapp-db
  instances: 3
  type: rw
  pgbouncer:
    poolMode: transaction
