apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup

metadata:
  name: myapp-db-daily-backup
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: backup

spec:
  schedule: '0 0 0 * * *'  # Every day at midnight
  cluster:
    name: myapp-db
