apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-ingress

resources:
  - namespace.yaml
  - shared-gateway-dev.yaml
  - shared-gateway-stage.yaml
  - shared-gateway-prod.yaml