apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: false
    pairs:
      app: myapp

configMapGenerator:
  - name: myapp-config
    literals:
      - SERVER_PORT=8080
      - SERVER_TIMEOUT_READ=3s
      - SERVER_TIMEOUT_WRITE=5s
      - SERVER_TIMEOUT_IDLE=5s
      - SERVER_DEBUG=true
      - DB_PORT=5432
      - DB_DEBUG=false
