apiVersion: v1
kind: Service

metadata:
  name: myapp-app
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: api

spec:
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: api
  ports:
    - port: 8001
      targetPort: httpport # matches with Deployment
      name: http
