apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - namespace.yaml
  - istio-ambient-manifest.yaml
  - prometheus-addon.yaml
  - kiali-addon.yaml
  - grafana-addon.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: '3'
