apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-app-config
  namespace: myapp
  labels:
    app: myapp-app-config
data:
  DEBUG: 'false'
  SERVER_PORT: '8080'
  SERVER_TIMEOUT_READ: '3s'
  SERVER_TIMEOUT_WRITE: '5s'
  SERVER_TIMEOUT_IDLE: '5s'
  DB_HOST: 'TODO: Update according to production env'
  DB_PORT: '5432'
  DB_USER: 'TODO: Update according to production env'
  DB_NAME: 'TODO: Update according to production env'