apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.8.0/components.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: '1'
